Lambda Layer Update - Latest Published Layer ARNs for Jan 2022 release
aws-observability/aws-otel-lambda pull request #220
Opened 2022-02-02 22:58 UTC by vasireddy99

Description:

Updates the layer.tf and template.yml file to have the latest Lambda Layer ARNs for the layers released as part of Jan 2022 release.

This includes OTel Python 1.9.1 & ADOT Collector 0.43.1

Link to tracking Issue:

N/A

Testing:

Covered by Soaking Tests.

Documentation:

N/A

2022-02-02 23:01 UTC, wangzlei approved these changes

2022-02-02 23:49 UTC, NathanielRN requested changes

2022-02-02 23:49 UTC, NathanielRN commented on python/sample-apps/aws-sdk/deploy/wrapper/layer_amd64.tf
> +}
Missing new line

2022-02-02 23:49 UTC, NathanielRN commented on sample-apps/python-aws-sdk-aiohttp-sam/template.yml
> +      layer: "arn:aws:lambda:us-west-2:901920570463:layer:aws-otel-python38-amd64-ver-1-9-1:1"
Let's add the new line

2022-02-02 23:49 UTC, NathanielRN commented on dotnet/sample-apps/aws-sdk/deploy/wrapper/layer_amd64.tf
>  locals {
We also need to update `go` layer ARNs!

2022-02-02 23:49 UTC, NathanielRN commented on dotnet/sample-apps/aws-sdk/deploy/wrapper/layer_amd64.tf
> -  collector_layer_arns_amd64 = {
We shouldn't change the spacing, let's put these spaces back.

2022-02-03 00:29 UTC, NathanielRN approved these changes
Thank you for this! Let's go!!

2022-02-03 00:31 UTC, merged