Lamba Layer Release - March 2022 Update layer versions in README.md
aws-observability/aws-otel-lambda pull request #235
Opened 2022-03-08 16:41 UTC by vasireddy99

Description:

This PR updates the README.md and changelog.md with respective versions for Python, NodeJS, Java-agent, Java-wrapper and collector layers

Documentation:
It is a documentation change

2022-03-08 16:49 UTC, bryan-aguilar commented on CHANGELOG.md
> +- Collector layer **aws-otel-collector-ver-0-45-0** contains ADOT Collector for Lambda `v0.17.0`.
Is ADOT Collector for Lambda the correct terminology?

2022-03-08 16:49 UTC, bryan-aguilar commented on README.md
> +- Collector layer **aws-otel-collector-ver-0-45-0** contains ADOT Collector for Lambda `v0.17.0`. Compatible with [.NET](https://aws-otel.github.io/docs/getting-started/lambda/lambda-dotnet) and [Go]
Same issue with the term `ADOT Collector for Lambda`

2022-03-08 17:38 UTC, NathanielRN approved these changes
Left some wording suggestions. Thanks!

2022-03-08 17:38 UTC, NathanielRN commented on CHANGELOG.md
> +**AWS Distro For OpenTelemetry lambda now supports ARM64 Architecture**
```suggestion
**AWS Distro For OpenTelemetry Lambda now supports ARM64 Architecture**
```

2022-03-08 17:38 UTC, NathanielRN commented on CHANGELOG.md
> +- Layers cover 16 AWS Regions: us-east-1, us-east-2, us-west-1, us-west-2, ap-south-1, ap-northeast-2, ap-southeast-1, ap-southeast-2, ap-northeast-1, ca-central-1, eu-central-1, eu-west-1, eu-west-2
```suggestion
- x86_64 Layers cover 16 AWS Regions: us-east-1, us-east-2, us-west-1, us-west-2, ap-south-1, ap-northeast-2, ap-southeast-1, ap-southeast-2, ap-northeast-1, ca-central-1, eu-central-1, eu-west-1, eu-west-2, eu-west-3, eu-north-1, sa-east-1
- ARM64 Layers cover 10 AWS Regions: us-east-1, us-east-2, us-west-2, ap-south-1, ap-southeast-1, ap-southeast-2, ap-northeast-1, eu-central-1, eu-west-1, eu-west-2
```

2022-03-08 17:58 UTC, NathanielRN requested changes
Critical changes to the architecture component of the layer names.

2022-03-08 17:58 UTC, NathanielRN commented on README.md
> +- Collector layer **aws-otel-collector-ver-0-45-0** contains ADOT Collector for Lambda `v0.17.0`. Compatible with [.NET](https://aws-otel.github.io/docs/getting-started/lambda/lambda-dotnet) and [Go]
Need to add `<amd64|arm64>-` to all of these lines.

2022-03-08 18:32 UTC, vasireddy99 commented
> Critical changes to the architecture component of the layer names.

Thanks for the call out, committed those changes

2022-03-09 00:02 UTC, NathanielRN approved these changes

2022-03-09 00:02 UTC, merged